version: '3.7'
services:
  node-app:
    build: gate-simulator
    image: gate-simulator:1.0
    ports:
      - '9999:9999'
  mysql:
    image: mysql:8.0
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass

  postgresql:
    image: postgres:12-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres:/var/lib/postgres
    environment:
      - POSTGRES_RANDOM_ROOT_PASSWORD=yes
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass